### ISSUE TITLE
Returning an function instead of the json-string (make_query)

### ISSUE THREAD

**Issue by Beastcraft** [tsileo/cube-client#3]
While trying to get an event via c.event("foobar"), it always returns an bound method. (Probably something changed in the newer versions of Request)

cube.py, Line 49: 
Change 'return r.json' to 'r.json()' and it works like a charm

p.s. same with returning the types (cube.py, Line 69)

**Comment by tsileo** [comment]
Fixed.

Thanks!

**Comment by Beastcraft** [comment]
Nice, thanks :-)
